[package]
name = "control-interface"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
rmp-serde = "0.15.0"
serde_bytes = "0.11.5"
nats = "0.8.6"
actix-rt = "1.1.1"
futures = "0.3.8"
wascap = "0.5.1"
uuid = {version = "0.8", features  = ["serde", "v4"]}
ring = "0.16.19"
data-encoding = "2.3.1"
