[package]
name = "wasmcloud"
version = "0.15.0"
authors = ["wasmCloud Team"]
edition = "2018"
default-run = "wasmcloud"
license-file = "LICENSE"
description = "A secure, distributed, WebAssembly actor model runtime for the cloud, edge, and everything in between"
repository = "https://github.com/wasmcloud/wasmcloud"
documentation = "https://wasmcloud.dev"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "wasmcloud",
    "webassembly",
    "actor",
]
categories = [
    "wasm", "api-bindings", "command-line-utilities"
]
exclude = [    
    "demos/*",
    ".github/*",
    ".gitignore"
]
autotests = false

[[test]]
name = "integration"
path = "tests/lib.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
wapc = { version = "0.10.1" }
log = "0.4.11"
env_logger = "0.8.2"
anyhow = "1.0.34"
wasmcloud-host = { path = "crates/wasmcloud-host", version = "0.15.0" }
actix-rt = "1.1.1"
nats = "0.8.6"
structopt = "0.3.21"
nkeys = "0.0.11"

[dev-dependencies]
rmp-serde = "0.14.4"
serde = {version = "1.0.117", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.59"
provider-archive = "0.4.0"
redis = "0.17.0"
reqwest = { version = "0.10"}
uuid = { version = "0.8", features = ["serde", "v4"] }
nats = "0.8.5"
wasmcloud-httpserver = { version = "0.11.1", features = ["static_plugin"] }
wasmcloud-redis = { version = "0.11.1", features = ["static_plugin"] }
wasmcloud-control-interface = { path = "./crates/wasmcloud-control-interface"}
wasmcloud-actor-http-server = "0.1.0"
ctor = "0.1.16"
wascap = "0.6.0"
futures = "0.3.6"

[workspace]
members = [
    "crates/wasmcloud-host",
    "crates/wasmcloud-control-interface"
]


[[bin]]
name = "wasmcloud"
path = "src/wasmcloud.rs"

[[bin]]
name = "wasmcloud-lite"
path = "src/wasmcloud-lite.rs"
