[package]
name = "wasccd"
version = "0.15.0"
authors = [
    "Kevin Hoffman <alothien@gmail.com>",    
]
edition = "2018"
default-run = "wasccd"
license-file = "LICENSE"
description = "A secure, distributed, WebAssembly actor model runtime for the cloud, edge, and everything in between"
repository = "https://github.com/wascc/wasccd"
documentation = "https://wascc.dev"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "wascc",
    "webassembly",
    "actor",
]
categories = [
    "wasm", "api-bindings", "command-line-utilities"
]
exclude = [    
    "demos/*",
    ".github/*",
    ".gitignore"
]
autotests = false

[[test]]
name = "integration"
path = "tests/lib.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
wapc = { version = "0.10.1" }
log = "0.4.11"
env_logger = "0.7.1"
anyhow = "1.0.33"
wascc-host = { path = "./crates/wascc-host" }
lattice-rpc-nats = { path = "crates/lattice-rpc-nats" }
lattice-cplane-nats = { path = "crates/lattice-cplane-nats"}
actix-rt = "1.1.1"

[dev-dependencies]
rmp-serde = "0.14.4"
serde = {version = "1.0.117", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.59"
provider-archive = "0.3.0"
redis = "0.17.0"
reqwest = { version = "0.10"}
uuid = { version = "0.8", features = ["serde", "v4"] }

[workspace]
members = [
    "crates/wascc-host",
    "crates/lattice-rpc-nats",
    "crates/lattice-cplane-nats"
]


[[bin]]
name = "wasccd"
path = "src/wasccd.rs"

[[bin]]
name = "wasccd-lite"
path = "src/wasccd-lite.rs"
