[package]
name = "wasmcloud-provider-core"
version = "0.1.0"
authors = ["wasmcloud Team"]
edition = "2018"
description = "Core types and traits used for building wasmcloud capability providers"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-provider-core"
readme = "README.md"
keywords = ["webassembly", "wasm", "codec", "wascc"]
categories = ["wasm", "data-structures","encoding"]
homepage = "https://wasmcloud.dev"

[badges]
maintenance = { status = "active"}

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.115"
serde_bytes = "0.11.5"
rmp-serde = "0.15.4"

[dev-dependencies]
structopt = "0.3.17"
serde_json = "1.0.57"
base64 = "0.13.0"

# This is where the health check request/response types come from, 
# used for doctests
wasmcloud-actor-core = "0.2.2"

