[package]
name = "wasmcloud-control-interface"
version = "0.2.0"
authors = ["wasmCloud Team"]
edition = "2018"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmCloud/wasmCloud"
description = "This library is a convenient API for interacting with the lattice control interface."
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-control-interface"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "control", "ctl"]
categories = ["wasm", "api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
rmp-serde = "0.15.0"
serde_bytes = "0.11.5"
nats = "0.8.6"
actix-rt = "1.1.1"
futures = "0.3.8"
wascap = "0.6.0"
uuid = {version = "0.8", features  = ["serde", "v4"]}
ring = "0.16.19"
data-encoding = "2.3.1"
