name: CONTROL-INTERFACE

on:
  push:
    branches: [ main ]
    paths:
    - "crates/control-interface/**"
  pull_request:
    branches: [ main ]
    paths:
    - "crates/control-interface/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./crates/control-interface

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working-directory}}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{env.working-directory}}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{env.working-directory}}
